name: nure-jupyter-lab-works
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab=3
  - matplotlib=3.3
  - numpy=1.20
  - opencv=4.5
  - scikit-image=0.18
  - scikit-learn=0.24
  - joblib=1.0
